### ISSUE TITLE
Files that are already open in another pane are opened as inactive.

### ISSUE THREAD

**Issue by subsetpark** [SublimeText/InactivePanes#10] opened 2014-12-03 16:49 UTC
Steps to reproduce:

1. In Pane 1, open file A.
2. In Pane 2, open file B.
3. In Pane 2, using Goto Anything, open file A.
File A will show up as dimmed in Pane 2. Tabbing back to File B will be active, but File A will stay dim.

**Comment by donut** [comment] 2015-02-11 20:14
I was experiencing this as well and restarting ST3 fixed the issue.

**Comment by braingineer** [comment] 2015-03-28 00:07
Another way to reproduce that doesn't get fixed by restarting:

1. Open file A.
2. Go to file -> new view into file ; this will open file A again in a new tab
3. Put second_fileA into a different pane or window. 

Now both panes will be marked inactive (grayed out for me). 

Restarting does not fix.  Sublime will not restart with the second view into file A, it will close it.

**Comment by FichteFoll** [comment] 2015-04-08 07:36
Afaik the open file in different window approach does not actually create a clone, so you don't see changes made in one view immediately in the other one too. 

This is a bug in sublime text itself and nothing I can fix. I reported it on the github tracker recently with a repro so I hope it gets fixed soon. 

What I find weird however is that restarting closes on if the views for you. This may be caused by a different plugin.

**Comment by FichteFoll** [comment] 2015-08-21 15:39
As I said earlier, this is a bug caused by ST (https://github.com/SublimeTextIssues/Core/issues/731) and nothing I can fix. I should probably add a note in the readme and then close this issue.

**Comment by FichteFoll** [comment] 2015-08-24 21:47
Actually, this is already mentined in the readme (as I just remembered).

**Closed by FichteFoll** 2015-08-24 21:47 UTC
Labels: invalid
